=== Kaehl1/Green-Protocol/SchemaSalami.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="perfil">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="usuario"/>
                <xs:element ref="juego"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="juego">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="partidas"/>
                <xs:element ref="logros"/>
            </xs:sequence>
            <xs:attribute name="nombre" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="partidas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="partida" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="partida">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombreHeroe"/>
                <xs:element ref="clase"/>
                <xs:element ref="jefe"/>
                <xs:element ref="puntos"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="jefe">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre"/>
                <xs:element ref="clase"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="logros">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="logro" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="logro">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre"/>
                <xs:element ref="descripcion"/>
            </xs:sequence>
            <xs:attribute name="puntos" type="xs:integer"/>
            <xs:attribute name="completado" type="xs:string"/>
            <xs:attribute name="secreto" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="usuario" type="xs:string"/>
    <xs:element name="nombreHeroe" type="xs:string"/>
    <xs:element name="clase" type="xs:string"/>
    <xs:element name="nombre" type="xs:string"/>
    <xs:element name="puntos" type="xs:integer"/>
    <xs:element name="descripcion" type="xs:string"/>
</xs:schema>

=== Kaehl1/Green-Protocol/GreenProtocol.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="./GreenProtocol.xsl" type="text/xsl"?>
<perfil xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./SchemaSalami.xsd">
    <usuario>Kaehl</usuario>
    <juego nombre="Green Protocol">
        <partidas>
        </partidas>
        <logros>
            <logro puntos="5" completado="no" secreto="no">
                <nombre>Alcóholico</nombre>
                <descripcion>Has consumido una poción</descripcion>
            </logro>
            <logro puntos="5" completado="no" secreto="no">
                <nombre>¿Y este botón que hace?</nombre>
                <descripcion>Has utilizado tu habilidad especial</descripcion>
            </logro>
            <logro puntos="5" completado="no" secreto="no">
                <nombre>La primera regla</nombre>
                <descripcion>Has jugado tu primera partida</descripcion>
            </logro>
            <logro puntos="5" completado="no" secreto="no">
                <nombre>Bautismo de acero</nombre>
                <descripcion>Has jugado una partida siendo Guerrero</descripcion>
            </logro>
            <logro puntos="5" completado="no" secreto="no">
                <nombre>Cruzada personal</nombre>
                <descripcion>Has jugado una partida siendo Paladin</descripcion>
            </logro>
            <logro puntos="5" completado="no" secreto="no">
                <nombre>Presentación de credenciales</nombre>
                <descripcion>Has jugado una partida siendo Pícaro</descripcion>
            </logro>
            <logro puntos="10" completado="no" secreto="no">
                <nombre>Dominio del ring</nombre>
                <descripcion>Has ganado tu primera partida</descripcion>
            </logro>
            <logro puntos="10" completado="no" secreto="no">
                <nombre>La senda de la espada</nombre>
                <descripcion>Has ganado tu primera partida siendo Guerrero</descripcion>
            </logro>
            <logro puntos="10" completado="no" secreto="no">
                <nombre>Caminante del sol</nombre>
                <descripcion>Has ganado tu primera partida siendo Paladín</descripcion>
            </logro>
            <logro puntos="10" completado="no" secreto="no">
                <nombre>Veneno en las venas</nombre>
                <descripcion>Has ganado tu primera partida siendo Pícaro</descripcion>
            </logro>
            <logro puntos="10" completado="no" secreto="no">
                <nombre>Chatarra</nombre>
                <descripcion>Has ganado tu primera partida a un jefe Guerrero</descripcion>
            </logro>
            <logro puntos="10" completado="no" secreto="no">
                <nombre>Hereje</nombre>
                <descripcion>Has ganado tu primera partida a un jefe Paladín</descripcion>
            </logro>
            <logro puntos="10" completado="no" secreto="no">
                <nombre>Caza-ratas</nombre>
                <descripcion>Has ganado tu primera partida a un jefe Pícaro</descripcion>
            </logro>
            <logro puntos="15" completado="no" secreto="no">
                <nombre>Bajo control</nombre>
                <descripcion>Ganar una partida con 10HP o menos</descripcion>
            </logro>
            <logro puntos="15" completado="no" secreto="no">
                <nombre>Depredador Herido</nombre>
                <descripcion>Ganar una partida con 65HP o más</descripcion>
            </logro>
            <logro puntos="25" completado="no" secreto="si">
                <nombre>Freno facial</nombre>
                <descripcion>Has chocado contra un muro</descripcion>
            </logro>
            <logro puntos="25" completado="no" secreto="si">
                <nombre>Fantasma del ring</nombre>
                <descripcion>Has ganado una partida sin recibir daño</descripcion>
            </logro>
        </logros>
    </juego>
</perfil>
